# Generated by Django 4.0.5 on 2022-07-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_fst_name_profile_lst_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(default='Kayin', max_length=100),
        ),
    ]
