# Generated by Django 4.0.5 on 2022-07-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_location_profile_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
    ]
