# Generated by Django 4.0.5 on 2022-07-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('Sagaing', 'Sagaing'), ('Magway', 'Magway'), ('Kayin', 'Kayin'), ('Chin', 'Chin'), ('Mandalay', 'Mandalay'), ('Kayah', 'Kayah'), ('Rakhine', 'Rakhine'), ('Yangon', 'Yangon'), ('Mon', 'Mon'), ('Bago', 'Bago'), ('Tanintharyi', 'Tanintharyi'), ('Shan', 'Shan'), ('Kachin', 'Kachin'), ('Ayyerwady', 'Ayyerwady')], default='Kayin', max_length=100),
        ),
    ]
