# Generated by Django 4.0.5 on 2022-07-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(default='Kayin', max_length=100),
        ),
    ]
