# Generated by Django 4.0.5 on 2022-07-22 05:05

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profile_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 7, 22, 11, 35, 6, 145760))),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default='Burmese', max_length=100),
        ),
    ]
