# Generated by Django 4.0.5 on 2022-07-22 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_post_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='txt',
            field=models.TextField(default='.....'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 13, 18, 29, 34919)),
        ),
    ]
